### PR TITLE
Rm old core implementation from deployed file

### PR DESCRIPTION
**Pull request by gtupak**

### CODE REVIEW

**Review by xitronix — COMMENTED** [review]
Why do we want to remove it?

**Comment by gtupak** [comment]
The "first" version was added during development, and then changed to version "2", but we don't have official tests for that version 2. Now that this is the first official patch with proper tests, version 2 makes sense but there's already on there so I'm removing the old one and adding the new one in. In case we want to retrieve back the old implementation contract we can always look up on etherscan

**Review by xitronix — APPROVED** [review]
So shall we remove versioning then? And just replace it whenever we have new version?

**Comment by gtupak** [comment]
Honestly not against it, we should have a convo about it separate from this thread!

**Pull request merged**
